version: '2'
services:
  ddbgo:
    image: mbuechner/ddbgo:latest
    container_name: "ddbgo"
    restart: always
#    labels:
#      - "traefik.enable=true"
#      - "traefik.backend=drupal"
#      - "traefik.frontend.rule=Host:go-t.ddb.de"
    environment:
      MYSQL_HOSTNAME: "ddbgo.example.com"
      MYSQL_DATABASE: "myddbgodatabase"
      MYSQL_USER: "myddbgouser"
      MYSQL_PASSWORD: "myddbgopassword"
      MYSQL_PORT: "3306"
      HASH_SALT: "myverysecretddbgohashsalt"
      UPDATE_FREE_ACCESS: "FALSE"
      FILE_PUBLIC_PATH: "sites/default/files"
      TRUSTED_HOST_PATTERNS: "^localhost$$, ^127.0.0.1$$, ^go-t.ddb.de$$"
      APACHE_LOG_DIR: "/var/www/html/web/sites/default/files/logs"
    volumes:
      - ddbgo:/var/www/html/web/sites/default/files
    ports:
      - 80
#    networks:
#      - traefik
#networks:
#  traefik:
#    external:
#      name: traefik
