field.field.*.*.*.third_party.unique_field_ajax:
  type: mapping
  label: Unique field third party settings
  mapping:
    unique:
      type: boolean
      label: Set if field is unique or not
    warn_only:
      type: boolean
      label: 'Set if saving is always possible'
    per_lang:
      type: boolean
      label: Unique per language
    use_ajax:
      type: boolean
      label: Use ajax validation
    message:
      type: string
      label: Validation error message
node.type.*.third_party.unique_field_ajax:
  type: mapping
  label: 'Unique field node third party settings'
  mapping:
    unique_title:
      type: boolean
      label: 'Set if node requires unique titles'
    warn_only:
      type: boolean
      label: 'Set if saving is always possible'
    per_lang:
      type: boolean
      label: Unique per language
    use_ajax:
      type: boolean
      label: Use ajax validation
    message:
      type: string
      label: Validation error message
