{{- if and (eq .Values.platform.type "openshift") .Values.drupal.route.enabled }}
{{- $name := .Values.drupal.externalHost -}}
{{- include "ddbgo.assertAvailable" (dict "root" . "apiVersion" "route.openshift.io/v1" "kind" "Route" "name" $name) }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ddbgo.labels" . | nindent 4 }}
    app.kubernetes.io/component: drupal
  annotations:
    {{- include "ddbgo.protectionAnnotations" . | nindent 4 }}
    {{- with .Values.drupal.route.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  host: {{ .Values.drupal.externalHost }}
  to:
    kind: Service
    name: {{ include "ddbgo.drupalName" . }}
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
{{- end }}
